name: Release

on:
  push:
    branches:
      - preview

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm install

      - name: Run Semantic Release
        id: semantic
        run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # ✅ Extract version from package.json
      - name: Get Release Version
        id: get_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      # ✅ Notify Discord with the extracted version
      - name: Notify Discord (Preview Only)
        if: success() && github.ref == 'refs/heads/preview'
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "Release Bot",
            "embeds": [{
              "title": "🚀 New Preview Release!",
              "description": "A new **preview** release has been deployed.",
              "color": 16776960,
              "fields": [
                { "name": "Version", "value": "'"${VERSION}"'", "inline": true },
                { "name": "Branch", "value": "preview", "inline": true }
              ]
            }]
          }' ${{ secrets.DISCORD_WEBHOOK_URL }}
